### ISSUE TITLE
Position problems - Coords

### ISSUE THREAD

**Issue by Codmadnesspro** [PEMapModder/Small-ZC-Plugins#13]
I was using worldeditart quite allot today and while using the positions I found that the coords are not being taken right as I've moved to a different position and when doing //pos 2 it gave the same coords. Doing set then didn't work as they weren't the correct coords.
I made a quick video showing the issue found here
https://playmcpe.com/worldeditart.mp4
If video doesn't show up right click it and save target as then open on your PC.
This is preventing me from carrying on.
Thanks

**Comment by PEMapModder** [comment]
Does it still exist

**Comment by iJoshuaHD** [comment]
@PEMapModder nope. it doesnt exist. we have been using WEA in constructing our new Spawn :)

**Comment by PEMapModder** [comment]
Closed.

**Comment by iJoshuaHD** [comment]
:P

**Comment by PEMapModder** [comment]
Lol
