### ISSUE TITLE
cuboid "set" orphans client (ipad, 0.10.4) from server

### ISSUE THREAD

**Issue by eyau77** [PEMapModder/Small-ZC-Plugins#16]
Ive been using your plugin like crazy, it's fantastic! 

A strange thing started happening today though. I noticed that after I select a cuboid and replace with whatever block once, my client seems to lose communication with the server and I can issue no further commands. Just no response at all.  None of the standard server commands have any response, such as /list, etc.  I have to log out and log back in to keep going. I can continue editing with the client, but nothing sets saved. I'm not sure what could have caused this, but I did revert back to an old version of my map from a tar backup beforehand. Maybe something got corrupted, do you have any suggestions?

So I: 
//pos1
//pos2
//set 7

It successfully replaces and console shows the message, but no subsequent commands can be issued.  It's as if the client is orphaned.

**Comment by PEMapModder** [comment]
So, can you recreate the bug anytime now? Because if I can't recreate it, I can't know what caused it.

**Comment by MrPowerGamerBR** [comment]
I also can recreate it, this happens randomly.

When you //set, you can not issue any commands, every players online will be frozen (only for you), and, if you break/place blocks, it will be not synced to the Server, disconnecting and reconnecting to the server fixes the issue (until you use //set again)

**Comment by PEMapModder** [comment]
So are you sure it is related to this plugin?
Full guide to recreating it please?

**Comment by PEMapModder** [comment]
Also might it be caused by the lag led by editing many blocks?

**Comment by MrPowerGamerBR** [comment]
Yes, I'm just using WorldEditArt, PureChat and PurePerms, and this happened before I started using PureChat and PurePerms.

I think that this is caused by editing a lot of blocks (I know that this happened with editing 98 blocks), if is lag the cause, try adding a little delay when placing blocks (AsyncWorldEdit does the same thing, but, of course, for WorldEdit).

Running Soft PocketMine, if this changes something.

**Comment by MrPowerGamerBR** [comment]
To recreate it... I don't know, just //pos1 and //pos2 a large area and //set anyblockhere.

**Comment by PEMapModder** [comment]
Synchronous world edit will be supported on the future :)
So you're sure this issue is only caused by lag?

**Comment by MrPowerGamerBR** [comment]
I don't know if is caused by lag, I think that this happens because of a lot of block updates in the same second, but I may be wrong.

Also, I didn't test if this happens locally, I know that this happens when connecting to a external (not locallly) Server (With 512MB RAM allocated, Linux)

**Comment by llj070** [comment]
The same things happened to me ,after used //p1 //p2 //set 0   ,everytime  ,then I can't say anything ,can't send message ,but I can see the message other players send . ,and I have  to quit and join to fix

**Comment by PEMapModder** [comment]
Confirmed, this is a client side issue. By sending a lot of update block packets to a client, some issues happen with RakNet on the client, and therefore the clients only receive packets correctly but not send them. This issue, according to @shoghicp, shall be fixed/improved in `MCPE 0.11`.

**Comment by llj070** [comment]
@PEMapModder  do you use QQ ,we have a QQ group ,and want to invite you to join us ?Can you tell me ?

**Comment by llj070** [comment]
Or send your QQ to my email  84217613@qq.com , thanks .

**Comment by PEMapModder** [comment]
This is not a forum. And no, I do not have any active contact methods except PocketMine Forums, GitHub and Twitter.
