### ISSUE TITLE
Problem with make a cylinder

### ISSUE THREAD

**Issue by eddir** [PEMapModder/Small-ZC-Plugins#17]
Hello, I like your plugin. But I am can not make cylinder. Did this work? I am wrote /wea cylinder 5 5 5 to make cylinder with radius 5 and height 5, id 5. And this is not make, the chat send this work, but the blocks did not set. What I should do to make cylinder? Sorry for my bad english :)
Thank you.

**Comment by PEMapModder** [comment]
This is an **invalid** issue. This is WorldEditArt, not WorldEdit. The correct way to make a cylinder of radius <radius> and height <height> to blocks of <pattern> is:

//cyl <radius> <height>
//set <pattern>

You could add an extra parameter for the first command at the end to indicate which direction the cylinder should grow towards, default up.
