### ISSUE TITLE
some features not working 

### ISSUE THREAD

**Issue by Tolo0** [PEMapModder/Small-ZC-Plugins#26]
Copy, paste, wand, don't seem to work. Iv changed the configuration to true and it let's me copy but when I try to paste. Nothing.  And the wand doesn't work at all. Please fix. This is the best plugin ever and using copy paste would just make it more amazing.

**Comment by PEMapModder** [comment]
Yes, that's why I disabled it by default. This won't get fixed without a rewrite.

**Comment by Tolo0** [comment]
Will you be rewriting this in the future?

**Comment by PEMapModder** [comment]
May or may not.

**Comment by Tolo0** [comment]
Ok il keep my fingers crossed hoping you do 👍

**Comment by PEMapModder** [comment]
If there is ever a rewrite, it will be legendary. It would have things like world editing on console or even non-players, and undo and redo queues.

**Comment by Tolo0** [comment]
That would be legendary 😁
