### ISSUE TITLE
It dosen`t works

### ISSUE THREAD

**Issue by Infinitisky** [PEMapModder/Small-ZC-Plugins#29]
all that it says in the terminal is that: [Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/WorldEditArt_dev_build.phar/src/pemapmodder/worldeditart/utils/provider/player/SQLite3PlayerDataProvider" at line 12

**Comment by PEMapModder** [comment]
It is not ready yet.
