### ISSUE TITLE
I have a problem in WorldEditArt

### ISSUE THREAD

**Issue by PIANOCRAFT6000** [PEMapModder/Small-ZC-Plugins#30]
How do I turn off the //cuboid? //cuboid destroys our spawn, please help for this.

**Comment by PEMapModder** [comment]
I forgot to add the permissions for WorldEditArt commands. Meanwhile, just disable WorldEditArt when your server isn't whitelisted.

**Comment by PEMapModder** [comment]
I am going on a thorough rewrite on WorldEditArt that fixed everything and adds new bugs ;)
