### ISSUE TITLE
Update Please.

### ISSUE THREAD

**Issue by LordJoshie** [PEMapModder/Small-ZC-Plugins#32]
I'd appreciate your time with updating this plugin for php7 on PM 14.0 (also ImagicalMine) 

thanks.

**Comment by PEMapModder** [comment]
There are many plugins in this repo.
Also, I will not update any plugins for ImagicalMine.

**Comment by LordJoshie** [comment]
okay  don't update for ImagicalMine. LOL.
consider they're cross compatible.

but yah ..update
up plugin don't work bruh.

pointlesssss

**Comment by PEMapModder** [comment]
ImagicalMine has backwards-incompatible changes.
