### ISSUE TITLE
Incompatible api for world edit art

### ISSUE THREAD

**Issue by kabluinc** [PEMapModder/Small-ZC-Plugins#34]
I'm using the latest world edit art from your repository but when I run pocket mine it says incompatible api.

I'm using ImagicalMine which is php7 and api 1.4

Iv tried using plugin api version bumper to change it to 1.4 but still it says incompatible api. Previous Dev builds load but end up with segmentation fault

**Comment by PEMapModder** [comment]
WorldEditArt has been thoroughly rewritten. The version in this repo is no longer supported.
